apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
  labels:
    app: kitchen
spec:
  selector:
    matchLabels:
      app: kitchen
  template:
    metadata:
      labels:
        app: kitchen
    spec:
      containers:
      - name: kitchen
        image: kitchen-image
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kitchen
  labels:
    app: kitchen
spec:
  selector:
    app: kitchen
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080